"use client";

import SidebarNav from "@/components/sidebarNav/SidebarNav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Menu from "@/components/menu/Menu";
import localFont from "@next/font/local";
import "@/assets/fonts/fonts-yekan/style.css";
import { useRef, useState, useEffect } from "react";
import { useRouter, usePathname } from "next/navigation";
import Login from "@/components/login/Login";
import { useLocation, useNavigate } from "react-router-dom";
import SidebarMenu from "@/components/sidebarNav/SidebarMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const mainSection = useRef<HTMLInputElement>(null);
  const [changeMenu, setChangeMenu] = useState(false);

  const changeNavbarStyle = () => {
    if (
      mainSection?.current?.scrollTop &&
      mainSection?.current?.scrollTop >= 80
    ) {
      setChangeMenu(true);
    } else {
      setChangeMenu(false);
    }
  };

  const [authenticated, setAuthenticated] = useState(
    Boolean(localStorage.getItem("token")) || true
  );

  const router = useRouter();
  const pathname = usePathname();

  useEffect(() => {
    if (pathname === "/login" && authenticated) {
      router.push("/roles");
    }
  }, [authenticated, pathname, router]);

  useEffect(() => {
    mainSection?.current?.addEventListener("scroll", changeNavbarStyle);
    // !localStorage?.getItem("token") && router.push("/login");
  }, []);

  return (
    <html lang="en" dir="rtl">
      <body style={{ fontFamily: "yekan" }} className="h-screen">
        {authenticated ? (
          <div className="flex w-full h-screen">
            <div className="sticky top-0 w-1/4 h-screen py-10 mr-10">
              {/* <SidebarNav /> */}
              <SidebarMenu />
            </div>
            <div className="w-full h-screen py-10 mx-10 overflow-scroll">
              {/* <Menu /> */}
              {children}
            </div>
          </div>
        ) : (
          <Login setAuthenticated={setAuthenticated} />
        )}
      </body>
    </html>
  );
}
