"use client";

import SidebarNav from "@/components/sidebarNav/SidebarNav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Menu from "@/components/menu/Menu";
import localFont from "@next/font/local";
import "@/assets/fonts/fonts-yekan/style.css";
import { useRef, useState, useEffect } from "react";
import { useRouter, usePathname } from "next/navigation";
import Login from "@/components/login/Login";
import { useLocation, useNavigate } from "react-router-dom";
import SidebarMenu from "@/components/sidebarNav/SidebarMenu";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import MobileMenu from "@/components/mobileMenu/MobileMenu";
import { faBars, faXmark } from "@fortawesome/free-solid-svg-icons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const mainSection = useRef<HTMLInputElement>(null);
  const [changeMenu, setChangeMenu] = useState(false);

  const changeNavbarStyle = () => {
    if (
      mainSection?.current?.scrollTop &&
      mainSection?.current?.scrollTop >= 80
    ) {
      setChangeMenu(true);
    } else {
      setChangeMenu(false);
    }
  };

  const [authenticated, setAuthenticated] = useState(
    localStorage.getItem("token") || true
  );

  const router = useRouter();
  const pathname = usePathname();

  useEffect(() => {
    if (pathname === "/login" && authenticated) {
      router.push("/roles");
    }
  }, [authenticated, pathname, router]);

  useEffect(() => {
    mainSection?.current?.addEventListener("scroll", changeNavbarStyle);
    // !localStorage?.getItem("token") && router.push("/login");
  }, []);

  const [showMobileMenu, setShowMobileMenu] = useState(false);

  return (
    <html lang="en" dir="rtl">
      <body style={{ fontFamily: "yekan" }} className="h-screen ">
        {authenticated ? (
          <div className="flex w-full h-screen">
            <div className="sticky top-0 hidden w-1/4 h-screen py-10 mr-10 lg:block">
              {/* <SidebarNav /> */}
              <SidebarMenu />
            </div>
            <div
              className="absolute top-0 right-0 z-20 m-5 lg:hidden"
              onClick={() => setShowMobileMenu(true)}
            >
              <FontAwesomeIcon icon={faBars} size="xl" />
            </div>
            {showMobileMenu && (
              <div className="absolute top-0 z-20 w-1/4 h-screen py-10 bg-white lg:hidden">
                {/* <SidebarNav /> */}
                <div className="absolute top-3 left-3">
                  <FontAwesomeIcon
                    icon={faXmark}
                    width={"20px"}
                    size="xl"
                    onClick={() => setShowMobileMenu(false)}
                  />
                </div>
                <MobileMenu />
              </div>
            )}

            <div className="w-full h-screen py-10 mx-10 overflow-scroll">
              {/* <Menu /> */}
              {children}
            </div>
          </div>
        ) : (
          <Login setAuthenticated={setAuthenticated} />
        )}
      </body>
    </html>
  );
}
